### ISSUE TITLE
Double-Click in Library replaces current playlist

### ISSUE THREAD

**Issue by schnittchen** [TheStalwart/Theremin#10]
...instead of appending to it. I guess most people find this confusing like me.

This could also be configurable.

**Comment by TheStalwart** [comment]
I'm not interested in implementing this feature myself. If anyone is looking for a feature to contribute, i will happily merge well coded pull request.

**Comment by schnittchen** [comment]
Too bad I'm not doing any development on MacOS, I'd be happy to jump in here!

**Comment by perelin** [comment]
I was annoyed with this as well but a look in the Preferences->Misc revealed the option to append on double-click.

**Comment by schnittchen** [comment]
I have that option enabled. The point is that is replaces the playlist by default, for appending I have to right-click or drag+drop.

**Comment by perelin** [comment]
Im running Theremin_0.7_experimental (20130331). For me setting the option "Double click in Library" in Preferences->Misc to "Appends" double-clicking a song in the library correctly appends the song to the end of the current playlist. Setting the option back to "Replaces" double-clicking a song in the library replaces the whole current playlist with just that song.

**Comment by schnittchen** [comment]
Works exactly as @perelin described. Sorry for overlooking that.
