### ISSUE TITLE
Music control keys on the keyboard

### ISSUE THREAD

**Issue by Sanic** [TheStalwart/Theremin#2]
I switched to MPD + Theramine this week and i totally love it.
The only thing i miss right now, is the support of the music control keys on the keyboard.
It would be totally awesome to control theramine with these keys to pause/unpause the playback quickly.
Is it possible to support this?

**Comment by TheStalwart** [comment]
I've been implementing media control key support for customer's iOS app just yesterday, but unfortunately, OS X doesn't have nice and simple public API for that. I might give https://github.com/nevyn/SPMediaKeyTap a try someday

**Comment by Sanic** [comment]
I would appreciate that. Thanks :+1:

**Comment by leolobato** [comment]
Issued a pull request with media keys support using SPMediaKeyTap.

I've used my fork since I've registered Theremin's bundle on SPMediaKeyTap. Once they've merged my fork back to master, we can update the submodule to point to https://github.com/nevyn/SPMediaKeyTap.

**Comment by TheStalwart** [comment]
Thanks Leo!
