### ISSUE TITLE
Could not connect to Localhost

### ISSUE THREAD

**Issue by hellofishy** [TheStalwart/Theremin#22]
Any idea how to solve this?

**Comment by mkody** [comment]
Well, you're not helping. 

Are you sure MPD is running? You might stop and start it again.
`mpd --kill && mpd`

**Comment by hellofishy** [comment]
Was just asking...very new to this.  Anyway I figured it out. thanks

**Comment by mkody** [comment]
Oh, great! You might close this issue then. :+1:
