### ISSUE TITLE
Get Info doesn't work

### ISSUE THREAD

**Issue by mafrosis** [TheStalwart/Theremin#5]
I just noticed on the current stable build "Get Info" doesn't open a popup.

**Comment by TheStalwart** [comment]
Get "Experimental" build, it's not any more broken than "Stable" nowadays

**Comment by mafrosis** [comment]
@TheStalwart thanks. Probably worth updating the README since any visitors will download the stable build like I did just now.

**Comment by TheStalwart** [comment]
Well, README clearly states that experimental version has more features. Stable version is there in case i break something in dev branch.
